import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const Home: NextPage = () => {
  const [currentPlayer, setCurrentPlayer] = useState("player X");
  return (
    <>
      <Head>
        <title>tic tac toe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" p-10">
        <div className="text-center">its {currentPlayer}s turn</div>
        <div className="flex justify-center">
          <div className="min-h-[200px] min-w-[200px]  border-2 border-black"></div>
          <div className="min-h-[200px] min-w-[200px] border-2 border-black"></div>
          <div className="min-h-[200px] min-w-[200px]  border-2 border-black"></div>
        </div>

        <div className="flex justify-center">
          <div className="min-h-[200px] min-w-[200px]  border-2 border-black"></div>
          <div className="min-h-[200px] min-w-[200px]  border-2 border-black"></div>
          <div className="min-h-[200px] min-w-[200px]  border-2 border-black"></div>
        </div>

        <div className="flex justify-center">
          <div className="min-h-[200px] min-w-[200px]  border-2 border-black"></div>{" "}
          <div className="min-h-[200px] min-w-[200px]  border-2 border-black"></div>
          <div className="min-w-[200px]  border-2 border-black"></div>
        </div>
      </main>
    </>
  );
};

export default Home;
